name: Keep Render Awake

on:
  schedule:
    # every 10 minutes
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: |
          curl -fsS https://flask-payment-api.onrender.com/health
