name: Keep Render Awake

on:
  schedule:
    # every 10 minutes, offset to avoid GitHub Actions high-load minutes
    - cron: "3,13,23,33,43,53 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: |
          curl -fsS https://flask-payment-api.onrender.com/health
